spring.application.name=app-service

# Configuración de Base de Datos (usando variables de entorno del docker-compose)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/MyDatabase?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER_NAME:root}
spring.datasource.password=${DB_PASSWORD:ESCORIAL}

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# Configuración del servidor
server.servlet.context-path=/appservice
#Puerto por defecto en el contenedor docker, no del PC
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE